cursor_shape          Underline
cursor_underline_thickness 1
window_padding_width  20

# Special
foreground #78898d
background #001b21

# Black
color0 #414868
color8 #414868

# Red
color1 #be3830
color9 #be3830

# Green
color2  #8b9c00
color10 #8b9c00

# Yellow
color3  #aa8d00
color11 #aa8d00

# Blue
color4  #5688d3
color12 #5688d3

# Magenta
color5  #b73784
color13 #b73784

# Cyan
color6  #62a199
color14 #62a199

# White
color7  #c0caf5
color15 #c0caf5

# Cursor
cursor #728284
cursor_text_color #092a37

# Selection highlight
selection_foreground #879696
selection_background #0a2e3c
